#!/bin/csh
#
#  check to see if a molecule name is given
#
if ($#argv < 1) then
echo "no molecule name given, you BOZO\!\!"
goto exit
endif
if ($#argv < 2) then
echo "give scratch directory, you BOZO\!\!"
goto exit
endif
#
#  set file definitions
#
set scrd=$2/$1.molfdir
#
#  clean up scratch
#  check to see if the directory exists
#
if (-e $scrd) then
rm -r $scrd
else
echo "there is no directory $scrd"
endif
exit:
